{
  "formatVersion": "1.1",
  "component": {
    "group": "org.meowcat",
    "module": "kato-gradle-plugin",
    "version": "0.1.0-dev31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.jengelman.gradle.plugins",
          "module": "shadow",
          "version": {
            "requires": "6.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kato-gradle-plugin-0.1.0-dev31.jar",
          "url": "kato-gradle-plugin-0.1.0-dev31.jar",
          "size": 17317,
          "sha512": "8c815d58dfd37681d425c64ec5cd5312e57ecfbe5b39a65df2b175de3e4f9912cc3d1b62d58bb99ca02e77aa85ed3e217a6a025bc48160d12e041d1636a1af55",
          "sha256": "1fc80adcfc953b1e13d016dadd7a0ba29e3e4a566f9455be13f80ed355558f5d",
          "sha1": "e55c9f1cce4e550f2bb69d943c55b46471b4af8e",
          "md5": "8c8cb14d73e65062df5c93a8ff664ecd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.jengelman.gradle.plugins",
          "module": "shadow",
          "version": {
            "requires": "6.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kato-gradle-plugin-0.1.0-dev31.jar",
          "url": "kato-gradle-plugin-0.1.0-dev31.jar",
          "size": 17317,
          "sha512": "8c815d58dfd37681d425c64ec5cd5312e57ecfbe5b39a65df2b175de3e4f9912cc3d1b62d58bb99ca02e77aa85ed3e217a6a025bc48160d12e041d1636a1af55",
          "sha256": "1fc80adcfc953b1e13d016dadd7a0ba29e3e4a566f9455be13f80ed355558f5d",
          "sha1": "e55c9f1cce4e550f2bb69d943c55b46471b4af8e",
          "md5": "8c8cb14d73e65062df5c93a8ff664ecd"
        }
      ]
    }
  ]
}
